### verificar conexao com produtos
GET http://localhost:3000/produtos

### verificar conexao com pedidos
GET http://localhost:3000/pedidos

### verificar conexao com clientes
GET http://localhost:3000/clientes

### criando cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
  "nome": "Agnaldo",
  "sobrenome": "Freitas",
  "telefone": "446767676769",
  "email": "aaaaaa@email.com"
}

### criando pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "cliente_id": 5,
  "produtoId": 2,
  "quantidade": 1
}

### Criar prod
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "sapatilha",
  "preco": 365
}