### Listar pedidos
GET http://localhost:3002/pedidos

### Criar pedido
POST http://localhost:3002/produtos
Content-Type: application/json

{
  "nome": "Teclado",
  "preco": 150
}

### Buscar pedido por ID
GET http://localhost:3001/produtos